#!/bin/sh

phpize
./configure --with-cpu=native
if [ $? -eq 0 ]; then
  make clean
  export EXTRA_CFLAGS
  EXTRA_CFLAGS="-fprofile-generate -DQB_DISABLE_MULTITHREADING -DQB_DISABLE_NATIVE_COMPILATION"
  make
  export NO_INTERACTION=1
  make test TESTS=tests/use-case-*.phpt
  unset NO_INTERACTION
  rm *.lo
  EXTRA_CFLAGS="-fprofile-use"
  make
  unset EXTRA_CFLAGS
  strip modules/qb.so
fi