#!/bin/sh

phpize
./configure --with-cpu=native
make clean
export EXTRA_CFLAGS
EXTRA_CFLAGS="-fprofile-generate -DQB_DISABLE_MULTITHREADING"
make
export NO_INTERACTION=1
make test TESTS=ext/qb/tests/use-case-*.phpt
unset NO_INTERACTION
rm *.lo
EXTRA_CFLAGS="-fprofile-use"
make
unset EXTRA_CFLAGS
strip modules/qb.so

