#!/bin/sh

extdir=`php -i 2> /dev/null | sed -n '/extension_dir => \(.*\) => .*/{s//\1/p;q}'`
if [ ! -d "$extdir" ] ; then
  mkdir "$extdir"
fi
cp modules/qb.so "$extdir\qb.so"

inidir=`php --ini 2> /dev/null | sed -n '/.*ini files in: \(.*\)/{s//\1/p;q}'`
if [ ! -z "$inidir" ] ; then
  if [ ! -f $inidir/qb.ini ] ; then
    if [ ! -d "$inidir" ] ; then
      mkdir "$inidir"
    fi
    cp qb.ini $inidir/qb.ini
  fi
else
  echo "Unable to determine PHP .ini path"
fi

