#!/bin/sh

extdir=`php -r "echo ini_get('extension_dir');" 2> /dev/null`
if [ ! -d "$extdir" ] ; then
  mkdir "$extdir"
fi
cp modules/qb.so "$extdir/qb.so"

inidir="/etc/php5/mods-available"
if [ ! -f $inidir/qb.ini ] ; then
  cp qb.ini $inidir/qb.ini
fi
php5enmod qb

