#!/bin/sh

extdir=`php -i 2> /dev/null | sed -n '/extension_dir => \(.*\) => .*/{s//\1/p;q}'`
if [ ! -d "$extdir" ] ; then
  mkdir "$extdir"
fi
cp modules/qb.so "$extdir\qb.so"

inidir="/etc/php5/mods-available"
if [ ! -f $inidir/qb.ini ] ; then
  cp qb.ini $inidir/qb.ini
fi
php5enmod qb

