/* Generated by re2c 0.13.5 on Mon Apr 07 00:59:16 2014 */
#line 3 "qb_parser_re2c.h"

enum YYCONDTYPE {
	yycINITIAL,
	yycENGINE_PARAM,
	yycINLINE_PARAM,
	yycPARAM,
	yycPARAM_DBL_QUOTES,
	yycPARAM_SG_QUOTES,
	yycTYPE_DECL,
	yycVARIABLE_NAME,
	yycCOMMENT,
};
