/* Generated by re2c 0.13.5 on Wed Apr 02 23:54:00 2014 */
#line 1 "qb_parser_re2c.l"
#include "qb.h"
#include "qb_parser_re2c.h"
#include "qb_parser_bison.h"

#define YYCTYPE				char
#define YYCURSOR 			l->cursor
#define YYMARKER			l->marker
#define YYCONDTYPE			int
#define YYGETCONDITION()	l->condition
#define YYSETCONDITION(c)	l->condition = c

int qb_scan_next_token(qb_lexer_context *l) {

skip:
	l->token = l->cursor; 


#line 21 "qb_parser_re2c.c"
	{
		YYCTYPE yych;
		switch (YYGETCONDITION()) {
		case yycCOMMENT: goto yyc_COMMENT;
		case yycINITIAL: goto yyc_INITIAL;
		case yycPARAM: goto yyc_PARAM;
		case yycPARAM_DBL_QUOTES: goto yyc_PARAM_DBL_QUOTES;
		case yycPARAM_SG_QUOTES: goto yyc_PARAM_SG_QUOTES;
		case yycTYPE_DECL: goto yyc_TYPE_DECL;
		case yycVARIABLE_NAME: goto yyc_VARIABLE_NAME;
		}
/* *********************************** */
yyc_COMMENT:

		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy4;
		case '\t':
		case ' ':	goto yy2;
		case '\n':
		case '\r':	goto yy8;
		default:	goto yy6;
		}
yy2:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy7;
yy3:
#line 173 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 52 "qb_parser_re2c.c"
yy4:
		++YYCURSOR;
#line 177 "qb_parser_re2c.l"
		{ return 0; }
#line 57 "qb_parser_re2c.c"
yy6:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy7:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':	goto yy3;
		default:	goto yy6;
		}
yy8:
		++YYCURSOR;
		YYSETCONDITION(yycINITIAL);
#line 175 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 73 "qb_parser_re2c.c"
/* *********************************** */
yyc_INITIAL:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy14;
		case '\t':
		case ' ':	goto yy12;
		case '\n':
		case '\r':	goto yy21;
		case '*':	goto yy18;
		case '/':	goto yy20;
		case '@':	goto yy16;
		default:	goto yy23;
		}
yy12:
		++YYCURSOR;
#line 179 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 100 "qb_parser_re2c.c"
yy14:
		++YYCURSOR;
#line 177 "qb_parser_re2c.l"
		{ return 0; }
#line 105 "qb_parser_re2c.c"
yy16:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 'e':	goto yy28;
		case 'g':	goto yy29;
		case 'i':	goto yy30;
		case 'l':	goto yy31;
		case 'p':	goto yy32;
		case 'r':	goto yy33;
		case 's':	goto yy34;
		case 'v':	goto yy35;
		default:	goto yy24;
		}
yy17:
		YYSETCONDITION(yycCOMMENT);
#line 171 "qb_parser_re2c.l"
		goto yyc_COMMENT;
#line 123 "qb_parser_re2c.c"
yy18:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy19;
		default:	goto yy23;
		}
yy19:
#line 164 "qb_parser_re2c.l"
		{ goto skip; }
#line 137 "qb_parser_re2c.c"
yy20:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '*':	goto yy25;
		default:	goto yy24;
		}
yy21:
		++YYCURSOR;
#line 168 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 148 "qb_parser_re2c.c"
yy23:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy24:
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy17;
		default:	goto yy23;
		}
yy25:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '*':	goto yy26;
		default:	goto yy24;
		}
yy26:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy27;
		default:	goto yy23;
		}
yy27:
#line 166 "qb_parser_re2c.l"
		{ goto skip; }
#line 180 "qb_parser_re2c.c"
yy28:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy100;
		default:	goto yy24;
		}
yy29:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy94;
		default:	goto yy24;
		}
yy30:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy88;
		default:	goto yy24;
		}
yy31:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy77;
		case 'o':	goto yy76;
		default:	goto yy24;
		}
yy32:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy63;
		case 'r':	goto yy64;
		default:	goto yy24;
		}
yy33:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy51;
		default:	goto yy24;
		}
yy34:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'h':	goto yy39;
		case 't':	goto yy40;
		default:	goto yy24;
		}
yy35:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy36;
		default:	goto yy24;
		}
yy36:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy37;
		default:	goto yy24;
		}
yy37:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy38;
		default:	goto yy23;
		}
yy38:
		YYSETCONDITION(yycTYPE_DECL);
#line 77 "qb_parser_re2c.l"
		{ return T_TAG_VAR; }
#line 252 "qb_parser_re2c.c"
yy39:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy46;
		default:	goto yy24;
		}
yy40:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy41;
		default:	goto yy24;
		}
yy41:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy42;
		default:	goto yy24;
		}
yy42:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy43;
		default:	goto yy24;
		}
yy43:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy44;
		default:	goto yy24;
		}
yy44:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy45;
		default:	goto yy23;
		}
yy45:
		YYSETCONDITION(yycTYPE_DECL);
#line 73 "qb_parser_re2c.l"
		{ return T_TAG_STATIC; }
#line 297 "qb_parser_re2c.c"
yy46:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy47;
		default:	goto yy24;
		}
yy47:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy48;
		default:	goto yy24;
		}
yy48:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy49;
		default:	goto yy24;
		}
yy49:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy50;
		default:	goto yy23;
		}
yy50:
		YYSETCONDITION(yycTYPE_DECL);
#line 67 "qb_parser_re2c.l"
		{ return T_TAG_SHARED; }
#line 330 "qb_parser_re2c.c"
yy51:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy52;
		case 't':	goto yy53;
		default:	goto yy24;
		}
yy52:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy58;
		default:	goto yy24;
		}
yy53:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'u':	goto yy54;
		default:	goto yy24;
		}
yy54:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy55;
		default:	goto yy24;
		}
yy55:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy56;
		default:	goto yy24;
		}
yy56:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy57;
		default:	goto yy23;
		}
yy57:
		YYSETCONDITION(yycTYPE_DECL);
#line 79 "qb_parser_re2c.l"
		{ return T_TAG_RETURN; }
#line 376 "qb_parser_re2c.c"
yy58:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy59;
		default:	goto yy24;
		}
yy59:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy60;
		default:	goto yy24;
		}
yy60:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy61;
		default:	goto yy24;
		}
yy61:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy62;
		default:	goto yy23;
		}
yy62:
		YYSETCONDITION(yycTYPE_DECL);
#line 81 "qb_parser_re2c.l"
		{ return T_TAG_RECEIVE; }
#line 409 "qb_parser_re2c.c"
yy63:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy72;
		default:	goto yy24;
		}
yy64:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy65;
		default:	goto yy24;
		}
yy65:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy66;
		default:	goto yy24;
		}
yy66:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy67;
		default:	goto yy24;
		}
yy67:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy68;
		default:	goto yy24;
		}
yy68:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy69;
		default:	goto yy24;
		}
yy69:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy70;
		default:	goto yy24;
		}
yy70:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy71;
		default:	goto yy23;
		}
yy71:
		YYSETCONDITION(yycTYPE_DECL);
#line 75 "qb_parser_re2c.l"
		{ return T_TAG_PROPERTY; }
#line 466 "qb_parser_re2c.c"
yy72:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy73;
		default:	goto yy24;
		}
yy73:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy74;
		default:	goto yy24;
		}
yy74:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy75;
		default:	goto yy23;
		}
yy75:
		YYSETCONDITION(yycTYPE_DECL);
#line 71 "qb_parser_re2c.l"
		{ return T_TAG_PARAM; }
#line 493 "qb_parser_re2c.c"
yy76:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy84;
		default:	goto yy24;
		}
yy77:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy78;
		default:	goto yy24;
		}
yy78:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy79;
		default:	goto yy24;
		}
yy79:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy80;
		default:	goto yy24;
		}
yy80:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy81;
		default:	goto yy24;
		}
yy81:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy82;
		default:	goto yy24;
		}
yy82:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy83;
		default:	goto yy23;
		}
yy83:
		YYSETCONDITION(yycTYPE_DECL);
#line 69 "qb_parser_re2c.l"
		{ return T_TAG_LEXICAL; }
#line 544 "qb_parser_re2c.c"
yy84:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy85;
		default:	goto yy24;
		}
yy85:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy86;
		default:	goto yy24;
		}
yy86:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy87;
		default:	goto yy23;
		}
yy87:
		YYSETCONDITION(yycTYPE_DECL);
#line 65 "qb_parser_re2c.l"
		{ return T_TAG_LOCAL; }
#line 571 "qb_parser_re2c.c"
yy88:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy89;
		default:	goto yy24;
		}
yy89:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy90;
		default:	goto yy24;
		}
yy90:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy91;
		default:	goto yy24;
		}
yy91:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy92;
		default:	goto yy24;
		}
yy92:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy93;
		default:	goto yy23;
		}
yy93:
		YYSETCONDITION(yycPARAM);
#line 41 "qb_parser_re2c.l"
		{ return T_TAG_ENGINE; }
#line 610 "qb_parser_re2c.c"
yy94:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy95;
		default:	goto yy24;
		}
yy95:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy96;
		default:	goto yy24;
		}
yy96:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy97;
		default:	goto yy24;
		}
yy97:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy98;
		default:	goto yy24;
		}
yy98:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy99;
		default:	goto yy23;
		}
yy99:
		YYSETCONDITION(yycTYPE_DECL);
#line 63 "qb_parser_re2c.l"
		{ return T_TAG_GLOBAL; }
#line 649 "qb_parser_re2c.c"
yy100:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy101;
		default:	goto yy24;
		}
yy101:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy102;
		default:	goto yy24;
		}
yy102:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy103;
		default:	goto yy24;
		}
yy103:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy104;
		default:	goto yy24;
		}
yy104:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy105;
		default:	goto yy23;
		}
yy105:
		YYSETCONDITION(yycPARAM);
#line 33 "qb_parser_re2c.l"
		{ return T_TAG_ENGINE; }
#line 688 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy111;
		case '\t':
		case ' ':	goto yy109;
		case '"':	goto yy116;
		case '\'':	goto yy118;
		case 'a':	goto yy114;
		case 'n':	goto yy115;
		case 'q':	goto yy113;
		default:	goto yy108;
		}
yy108:
		YYCURSOR = YYMARKER;
		goto yy132;
yy109:
		++YYCURSOR;
#line 179 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 718 "qb_parser_re2c.c"
yy111:
		++YYCURSOR;
#line 177 "qb_parser_re2c.l"
		{ return 0; }
#line 723 "qb_parser_re2c.c"
yy113:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy131;
		default:	goto yy108;
		}
yy114:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy125;
		default:	goto yy108;
		}
yy115:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy120;
		default:	goto yy108;
		}
yy116:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM_DBL_QUOTES);
#line 47 "qb_parser_re2c.l"
		{ goto skip; }
#line 747 "qb_parser_re2c.c"
yy118:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM_SG_QUOTES);
#line 55 "qb_parser_re2c.l"
		{ goto skip; }
#line 753 "qb_parser_re2c.c"
yy120:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy121;
		default:	goto yy108;
		}
yy121:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy122;
		default:	goto yy108;
		}
yy122:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy123;
		default:	goto yy108;
		}
yy123:
		++YYCURSOR;
#line 45 "qb_parser_re2c.l"
		{ return T_NEVER; }
#line 776 "qb_parser_re2c.c"
yy125:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'w':	goto yy126;
		default:	goto yy108;
		}
yy126:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy127;
		default:	goto yy108;
		}
yy127:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy128;
		default:	goto yy108;
		}
yy128:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 's':	goto yy129;
		default:	goto yy108;
		}
yy129:
		++YYCURSOR;
#line 43 "qb_parser_re2c.l"
		{ return T_ALWAYS; }
#line 805 "qb_parser_re2c.c"
yy131:
		yych = (YYCTYPE)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case '-':	goto yy133;
		default:	goto yy132;
		}
yy132:
#line 35 "qb_parser_re2c.l"
		{ return T_ENGINE_QB; }
#line 815 "qb_parser_re2c.c"
yy133:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy134;
		case 'n':	goto yy135;
		default:	goto yy108;
		}
yy134:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy142;
		default:	goto yy108;
		}
yy135:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy136;
		default:	goto yy108;
		}
yy136:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy137;
		default:	goto yy108;
		}
yy137:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy138;
		default:	goto yy108;
		}
yy138:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy139;
		default:	goto yy108;
		}
yy139:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy140;
		default:	goto yy108;
		}
yy140:
		++YYCURSOR;
#line 37 "qb_parser_re2c.l"
		{ return T_ENGINE_QB_NATIVE; }
#line 863 "qb_parser_re2c.c"
yy142:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy143;
		default:	goto yy108;
		}
yy143:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy144;
		default:	goto yy108;
		}
yy144:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy145;
		default:	goto yy108;
		}
yy145:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy146;
		default:	goto yy108;
		}
yy146:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy147;
		default:	goto yy108;
		}
yy147:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy148;
		default:	goto yy108;
		}
yy148:
		++YYCURSOR;
#line 39 "qb_parser_re2c.l"
		{ return T_ENGINE_QB_BYTECODE; }
#line 904 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM_DBL_QUOTES:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy154;
		case '\t':
		case ' ':	goto yy152;
		case '\n':
		case '\r':	goto yy159;
		case '"':	goto yy155;
		default:	goto yy157;
		}
yy152:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy158;
yy153:
#line 51 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 924 "qb_parser_re2c.c"
yy154:
		yych = (YYCTYPE)*++YYCURSOR;
		goto yy158;
yy155:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM);
#line 49 "qb_parser_re2c.l"
		{ goto skip; }
#line 933 "qb_parser_re2c.c"
yy157:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy158:
		switch (yych) {
		case '\n':
		case '\r':
		case '"':	goto yy153;
		default:	goto yy157;
		}
yy159:
		++YYCURSOR;
#line 53 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 948 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM_SG_QUOTES:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy165;
		case '\t':
		case ' ':	goto yy163;
		case '\n':
		case '\r':	goto yy170;
		case '\'':	goto yy166;
		default:	goto yy168;
		}
yy163:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy169;
yy164:
#line 59 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 968 "qb_parser_re2c.c"
yy165:
		yych = (YYCTYPE)*++YYCURSOR;
		goto yy169;
yy166:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM);
#line 57 "qb_parser_re2c.l"
		{ goto skip; }
#line 977 "qb_parser_re2c.c"
yy168:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy169:
		switch (yych) {
		case '\n':
		case '\r':
		case '\'':	goto yy164;
		default:	goto yy168;
		}
yy170:
		++YYCURSOR;
#line 61 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 992 "qb_parser_re2c.c"
/* *********************************** */
yyc_TYPE_DECL:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy177;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '+':
		case '-':
		case '.':
		case '/':
		case ';':
		case '=':
		case '@':
		case '\\':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy174;
		case '\t':
		case ' ':	goto yy175;
		case '$':	goto yy211;
		case '*':	goto yy197;
		case ',':	goto yy203;
		case '0':	goto yy205;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy207;
		case ':':	goto yy201;
		case '<':	goto yy193;
		case '>':	goto yy195;
		case '?':	goto yy199;
		case '[':	goto yy189;
		case ']':	goto yy191;
		case 'b':	goto yy187;
		case 'c':	goto yy186;
		case 'd':	goto yy183;
		case 'f':	goto yy182;
		case 'i':	goto yy179;
		case 'm':	goto yy188;
		case 's':	goto yy185;
		case 'u':	goto yy181;
		case 'v':	goto yy184;
		default:	goto yy209;
		}
yy174:
		YYCURSOR = YYMARKER;
		goto yy206;
yy175:
		++YYCURSOR;
#line 179 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 1097 "qb_parser_re2c.c"
yy177:
		++YYCURSOR;
#line 177 "qb_parser_re2c.l"
		{ return 0; }
#line 1102 "qb_parser_re2c.c"
yy179:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 'm':	goto yy297;
		case 'n':	goto yy298;
		default:	goto yy210;
		}
yy180:
#line 151 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1113 "qb_parser_re2c.c"
yy181:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy283;
		default:	goto yy210;
		}
yy182:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy272;
		default:	goto yy210;
		}
yy183:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy266;
		default:	goto yy210;
		}
yy184:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy253;
		case 'o':	goto yy254;
		default:	goto yy210;
		}
yy185:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy247;
		default:	goto yy210;
		}
yy186:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'h':	goto yy236;
		case 'o':	goto yy237;
		default:	goto yy210;
		}
yy187:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy229;
		default:	goto yy210;
		}
yy188:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy217;
		default:	goto yy210;
		}
yy189:
		++YYCURSOR;
#line 131 "qb_parser_re2c.l"
		{ return '['; }
#line 1168 "qb_parser_re2c.c"
yy191:
		++YYCURSOR;
#line 133 "qb_parser_re2c.l"
		{ return ']'; }
#line 1173 "qb_parser_re2c.c"
yy193:
		++YYCURSOR;
#line 135 "qb_parser_re2c.l"
		{ return '<'; }
#line 1178 "qb_parser_re2c.c"
yy195:
		++YYCURSOR;
#line 137 "qb_parser_re2c.l"
		{ return '>'; }
#line 1183 "qb_parser_re2c.c"
yy197:
		++YYCURSOR;
#line 139 "qb_parser_re2c.l"
		{ return '*'; }
#line 1188 "qb_parser_re2c.c"
yy199:
		++YYCURSOR;
#line 141 "qb_parser_re2c.l"
		{ return '?'; }
#line 1193 "qb_parser_re2c.c"
yy201:
		++YYCURSOR;
#line 143 "qb_parser_re2c.l"
		{ return ':'; }
#line 1198 "qb_parser_re2c.c"
yy203:
		++YYCURSOR;
#line 145 "qb_parser_re2c.l"
		{ return ','; }
#line 1203 "qb_parser_re2c.c"
yy205:
		yych = (YYCTYPE)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case 'x':	goto yy213;
		default:	goto yy208;
		}
yy206:
#line 147 "qb_parser_re2c.l"
		{ return T_DECIMAL; }
#line 1213 "qb_parser_re2c.c"
yy207:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy208:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy207;
		default:	goto yy206;
		}
yy209:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy210:
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy180;
		default:	goto yy209;
		}
yy211:
		++YYCURSOR;
		YYSETCONDITION(yycVARIABLE_NAME);
#line 153 "qb_parser_re2c.l"
		{ return '$'; }
#line 1307 "qb_parser_re2c.c"
yy213:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy214;
		default:	goto yy174;
		}
yy214:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy214;
		default:	goto yy216;
		}
yy216:
#line 149 "qb_parser_re2c.l"
		{ return T_HEXADECIMAL; }
#line 1366 "qb_parser_re2c.c"
yy217:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy218;
		default:	goto yy210;
		}
yy218:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy219;
		default:	goto yy210;
		}
yy219:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy220;
		default:	goto yy210;
		}
yy220:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy221;
		default:	goto yy210;
		}
yy221:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy222;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy223;
		default:	goto yy209;
		}
yy222:
#line 129 "qb_parser_re2c.l"
		{ return T_TYPE_MATRIX3X3; }
#line 1472 "qb_parser_re2c.c"
yy223:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy180;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy223;
		case 'x':	goto yy225;
		default:	goto yy209;
		}
yy225:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy226;
		default:	goto yy210;
		}
yy226:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy228;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy226;
		default:	goto yy209;
		}
yy228:
#line 127 "qb_parser_re2c.l"
		{ return T_TYPE_MATRIX; }
#line 1651 "qb_parser_re2c.c"
yy229:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy230;
		default:	goto yy210;
		}
yy230:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy231;
		default:	goto yy210;
		}
yy231:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy232;
		case 'e':	goto yy233;
		default:	goto yy209;
		}
yy232:
#line 115 "qb_parser_re2c.l"
		{ return T_TYPE_BOOLEAN; }
#line 1737 "qb_parser_re2c.c"
yy233:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy234;
		default:	goto yy210;
		}
yy234:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy235;
		default:	goto yy210;
		}
yy235:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy232;
		default:	goto yy209;
		}
yy236:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy244;
		default:	goto yy210;
		}
yy237:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy238;
		default:	goto yy210;
		}
yy238:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy239;
		default:	goto yy210;
		}
yy239:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy240;
		default:	goto yy210;
		}
yy240:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy241;
		default:	goto yy210;
		}
yy241:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy242;
		default:	goto yy210;
		}
yy242:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy243;
		default:	goto yy209;
		}
yy243:
#line 121 "qb_parser_re2c.l"
		{ return T_TYPE_COMPLEX; }
#line 1927 "qb_parser_re2c.c"
yy244:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy245;
		default:	goto yy210;
		}
yy245:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy246;
		default:	goto yy209;
		}
yy246:
#line 113 "qb_parser_re2c.l"
		{ return T_TYPE_CHAR; }
#line 2006 "qb_parser_re2c.c"
yy247:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy248;
		default:	goto yy210;
		}
yy248:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy249;
		default:	goto yy210;
		}
yy249:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy250;
		default:	goto yy210;
		}
yy250:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy251;
		default:	goto yy210;
		}
yy251:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy252;
		default:	goto yy209;
		}
yy252:
#line 111 "qb_parser_re2c.l"
		{ return T_TYPE_STRING; }
#line 2103 "qb_parser_re2c.c"
yy253:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy258;
		default:	goto yy210;
		}
yy254:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy255;
		default:	goto yy210;
		}
yy255:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy256;
		default:	goto yy210;
		}
yy256:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy257;
		default:	goto yy209;
		}
yy257:
#line 109 "qb_parser_re2c.l"
		{ return T_TYPE_VOID; }
#line 2194 "qb_parser_re2c.c"
yy258:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy259;
		default:	goto yy210;
		}
yy259:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy260;
		default:	goto yy210;
		}
yy260:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy261;
		default:	goto yy210;
		}
yy261:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy262;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy263;
		default:	goto yy209;
		}
yy262:
#line 125 "qb_parser_re2c.l"
		{ return T_TYPE_VECTOR3; }
#line 2294 "qb_parser_re2c.c"
yy263:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy265;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy263;
		default:	goto yy209;
		}
yy265:
#line 123 "qb_parser_re2c.l"
		{ return T_TYPE_VECTOR; }
#line 2378 "qb_parser_re2c.c"
yy266:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'u':	goto yy267;
		default:	goto yy210;
		}
yy267:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy268;
		default:	goto yy210;
		}
yy268:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy269;
		default:	goto yy210;
		}
yy269:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy270;
		default:	goto yy210;
		}
yy270:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy271;
		default:	goto yy209;
		}
yy271:
#line 103 "qb_parser_re2c.l"
		{ return T_TYPE_DOUBLE; }
#line 2475 "qb_parser_re2c.c"
yy272:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy273;
		default:	goto yy210;
		}
yy273:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy274;
		default:	goto yy210;
		}
yy274:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy275;
		default:	goto yy210;
		}
yy275:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy276;
		case '3':	goto yy277;
		case '6':	goto yy278;
		default:	goto yy209;
		}
yy276:
#line 101 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT; }
#line 2568 "qb_parser_re2c.c"
yy277:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy281;
		default:	goto yy210;
		}
yy278:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy279;
		default:	goto yy210;
		}
yy279:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy280;
		default:	goto yy209;
		}
yy280:
#line 107 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT64; }
#line 2653 "qb_parser_re2c.c"
yy281:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy282;
		default:	goto yy209;
		}
yy282:
#line 105 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT32; }
#line 2726 "qb_parser_re2c.c"
yy283:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy284;
		default:	goto yy210;
		}
yy284:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy285;
		default:	goto yy210;
		}
yy285:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '1':	goto yy288;
		case '3':	goto yy289;
		case '6':	goto yy290;
		case '8':	goto yy286;
		default:	goto yy210;
		}
yy286:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy287;
		default:	goto yy209;
		}
yy287:
#line 93 "qb_parser_re2c.l"
		{ return T_TYPE_UINT08; }
#line 2820 "qb_parser_re2c.c"
yy288:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '6':	goto yy295;
		default:	goto yy210;
		}
yy289:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy293;
		default:	goto yy210;
		}
yy290:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy291;
		default:	goto yy210;
		}
yy291:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy292;
		default:	goto yy209;
		}
yy292:
#line 99 "qb_parser_re2c.l"
		{ return T_TYPE_UINT64;	}
#line 2911 "qb_parser_re2c.c"
yy293:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy294;
		default:	goto yy209;
		}
yy294:
#line 97 "qb_parser_re2c.l"
		{ return T_TYPE_UINT32; }
#line 2984 "qb_parser_re2c.c"
yy295:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy296;
		default:	goto yy209;
		}
yy296:
#line 95 "qb_parser_re2c.l"
		{ return T_TYPE_UINT16; }
#line 3057 "qb_parser_re2c.c"
yy297:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy316;
		default:	goto yy210;
		}
yy298:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy299;
		default:	goto yy210;
		}
yy299:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy300;
		case '1':	goto yy301;
		case '3':	goto yy302;
		case '6':	goto yy303;
		case '8':	goto yy304;
		case 'e':	goto yy306;
		default:	goto yy209;
		}
yy300:
#line 83 "qb_parser_re2c.l"
		{ return T_TYPE_INT; }
#line 3147 "qb_parser_re2c.c"
yy301:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '6':	goto yy314;
		default:	goto yy210;
		}
yy302:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy312;
		default:	goto yy210;
		}
yy303:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy310;
		default:	goto yy210;
		}
yy304:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy305;
		default:	goto yy209;
		}
yy305:
#line 85 "qb_parser_re2c.l"
		{ return T_TYPE_INT08; }
#line 3238 "qb_parser_re2c.c"
yy306:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy307;
		default:	goto yy210;
		}
yy307:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy308;
		default:	goto yy210;
		}
yy308:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy309;
		default:	goto yy210;
		}
yy309:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy300;
		default:	goto yy209;
		}
yy310:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy311;
		default:	goto yy209;
		}
yy311:
#line 91 "qb_parser_re2c.l"
		{ return T_TYPE_INT64; }
#line 3398 "qb_parser_re2c.c"
yy312:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy313;
		default:	goto yy209;
		}
yy313:
#line 89 "qb_parser_re2c.l"
		{ return T_TYPE_INT32; }
#line 3471 "qb_parser_re2c.c"
yy314:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy315;
		default:	goto yy209;
		}
yy315:
#line 87 "qb_parser_re2c.l"
		{ return T_TYPE_INT16; }
#line 3544 "qb_parser_re2c.c"
yy316:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy317;
		default:	goto yy210;
		}
yy317:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy318;
		default:	goto yy210;
		}
yy318:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy319;
		case '1':
		case '2':
		case '3':
		case '4':	goto yy320;
		default:	goto yy209;
		}
yy319:
#line 119 "qb_parser_re2c.l"
		{ return T_TYPE_IMAGE4; }
#line 3633 "qb_parser_re2c.c"
yy320:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy321;
		default:	goto yy209;
		}
yy321:
#line 117 "qb_parser_re2c.l"
		{ return T_TYPE_IMAGE; }
#line 3706 "qb_parser_re2c.c"
/* *********************************** */
yyc_VARIABLE_NAME:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy327;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy332;
		case '\t':
		case ' ':	goto yy325;
		case '\n':
		case '\r':	goto yy324;
		default:	goto yy329;
		}
yy324:
yy325:
		++YYCURSOR;
#line 162 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 3792 "qb_parser_re2c.c"
yy327:
		++YYCURSOR;
#line 177 "qb_parser_re2c.l"
		{ return 0; }
#line 3797 "qb_parser_re2c.c"
yy329:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy331;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy332;
		default:	goto yy329;
		}
yy331:
		YYSETCONDITION(yycTYPE_DECL);
#line 156 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 3872 "qb_parser_re2c.c"
yy332:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy334;
		default:	goto yy332;
		}
yy334:
		YYSETCONDITION(yycTYPE_DECL);
#line 159 "qb_parser_re2c.l"
		{ return T_REGEXP; }
#line 3888 "qb_parser_re2c.c"
	}
#line 188 "qb_parser_re2c.l"

}
