/* Generated by re2c 0.13.5 */
#line 1 "qb_parser_re2c.l"
#include "qb.h"
#include "qb_parser_re2c.h"
#include "qb_parser_bison.h"

#define YYCTYPE				char
#define YYCURSOR 			l->cursor
#define YYMARKER			l->marker
#define YYCONDTYPE			int
#define YYGETCONDITION()	l->condition
#define YYSETCONDITION(c)	l->condition = c

int qb_scan_next_token(qb_lexer_context *l) {

skip:
	l->token = l->cursor; 


#line 21 "qb_parser_re2c.c"
	{
		YYCTYPE yych;
		switch (YYGETCONDITION()) {
		case yycCOMMENT: goto yyc_COMMENT;
		case yycENGINE_PARAM: goto yyc_ENGINE_PARAM;
		case yycINITIAL: goto yyc_INITIAL;
		case yycINLINE_PARAM: goto yyc_INLINE_PARAM;
		case yycPARAM: goto yyc_PARAM;
		case yycPARAM_DBL_QUOTES: goto yyc_PARAM_DBL_QUOTES;
		case yycPARAM_SG_QUOTES: goto yyc_PARAM_SG_QUOTES;
		case yycTYPE_DECL: goto yyc_TYPE_DECL;
		case yycVARIABLE_NAME: goto yyc_VARIABLE_NAME;
		}
/* *********************************** */
yyc_COMMENT:

		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy4;
		case '\t':
		case ' ':	goto yy2;
		case '\n':
		case '\r':	goto yy8;
		default:	goto yy6;
		}
yy2:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy7;
yy3:
#line 185 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 54 "qb_parser_re2c.c"
yy4:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 59 "qb_parser_re2c.c"
yy6:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy7:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':	goto yy3;
		default:	goto yy6;
		}
yy8:
		++YYCURSOR;
		YYSETCONDITION(yycINITIAL);
#line 187 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 75 "qb_parser_re2c.c"
/* *********************************** */
yyc_ENGINE_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy15;
		case '\t':
		case ' ':	goto yy13;
		case 'q':	goto yy17;
		default:	goto yy12;
		}
yy12:
		YYCURSOR = YYMARKER;
		goto yy19;
yy13:
		++YYCURSOR;
#line 191 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 101 "qb_parser_re2c.c"
yy15:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 106 "qb_parser_re2c.c"
yy17:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy18;
		default:	goto yy12;
		}
yy18:
		yych = (YYCTYPE)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case '-':	goto yy20;
		default:	goto yy19;
		}
yy19:
#line 41 "qb_parser_re2c.l"
		{ return T_ENGINE_QB; }
#line 122 "qb_parser_re2c.c"
yy20:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy21;
		case 'n':	goto yy22;
		default:	goto yy12;
		}
yy21:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy29;
		default:	goto yy12;
		}
yy22:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy23;
		default:	goto yy12;
		}
yy23:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy24;
		default:	goto yy12;
		}
yy24:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy25;
		default:	goto yy12;
		}
yy25:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy26;
		default:	goto yy12;
		}
yy26:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy27;
		default:	goto yy12;
		}
yy27:
		++YYCURSOR;
#line 43 "qb_parser_re2c.l"
		{ return T_ENGINE_QB_NATIVE; }
#line 170 "qb_parser_re2c.c"
yy29:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy30;
		default:	goto yy12;
		}
yy30:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy31;
		default:	goto yy12;
		}
yy31:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy32;
		default:	goto yy12;
		}
yy32:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy33;
		default:	goto yy12;
		}
yy33:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy34;
		default:	goto yy12;
		}
yy34:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy35;
		default:	goto yy12;
		}
yy35:
		++YYCURSOR;
#line 45 "qb_parser_re2c.l"
		{ return T_ENGINE_QB_BYTECODE; }
#line 211 "qb_parser_re2c.c"
/* *********************************** */
yyc_INITIAL:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy41;
		case '\t':
		case ' ':	goto yy39;
		case '\n':
		case '\r':	goto yy48;
		case '*':	goto yy45;
		case '/':	goto yy47;
		case '@':	goto yy43;
		default:	goto yy50;
		}
yy39:
		++YYCURSOR;
#line 191 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 238 "qb_parser_re2c.c"
yy41:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 243 "qb_parser_re2c.c"
yy43:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 'e':	goto yy55;
		case 'g':	goto yy56;
		case 'i':	goto yy57;
		case 'l':	goto yy58;
		case 'p':	goto yy59;
		case 'r':	goto yy60;
		case 's':	goto yy61;
		case 'v':	goto yy62;
		default:	goto yy51;
		}
yy44:
		YYSETCONDITION(yycCOMMENT);
#line 183 "qb_parser_re2c.l"
		goto yyc_COMMENT;
#line 261 "qb_parser_re2c.c"
yy45:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy46;
		default:	goto yy50;
		}
yy46:
#line 176 "qb_parser_re2c.l"
		{ goto skip; }
#line 275 "qb_parser_re2c.c"
yy47:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '*':	goto yy52;
		default:	goto yy51;
		}
yy48:
		++YYCURSOR;
#line 180 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 286 "qb_parser_re2c.c"
yy50:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy51:
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy44;
		default:	goto yy50;
		}
yy52:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '*':	goto yy53;
		default:	goto yy51;
		}
yy53:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy54;
		default:	goto yy50;
		}
yy54:
#line 178 "qb_parser_re2c.l"
		{ goto skip; }
#line 318 "qb_parser_re2c.c"
yy55:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy133;
		default:	goto yy51;
		}
yy56:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy127;
		default:	goto yy51;
		}
yy57:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy116;
		case 'n':	goto yy115;
		default:	goto yy51;
		}
yy58:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy104;
		case 'o':	goto yy103;
		default:	goto yy51;
		}
yy59:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy90;
		case 'r':	goto yy91;
		default:	goto yy51;
		}
yy60:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy78;
		default:	goto yy51;
		}
yy61:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'h':	goto yy66;
		case 't':	goto yy67;
		default:	goto yy51;
		}
yy62:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy63;
		default:	goto yy51;
		}
yy63:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy64;
		default:	goto yy51;
		}
yy64:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy65;
		default:	goto yy50;
		}
yy65:
		YYSETCONDITION(yycTYPE_DECL);
#line 87 "qb_parser_re2c.l"
		{ return T_TAG_VAR; }
#line 391 "qb_parser_re2c.c"
yy66:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy73;
		default:	goto yy51;
		}
yy67:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy68;
		default:	goto yy51;
		}
yy68:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy69;
		default:	goto yy51;
		}
yy69:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy70;
		default:	goto yy51;
		}
yy70:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy71;
		default:	goto yy51;
		}
yy71:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy72;
		default:	goto yy50;
		}
yy72:
		YYSETCONDITION(yycTYPE_DECL);
#line 83 "qb_parser_re2c.l"
		{ return T_TAG_STATIC; }
#line 436 "qb_parser_re2c.c"
yy73:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy74;
		default:	goto yy51;
		}
yy74:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy75;
		default:	goto yy51;
		}
yy75:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy76;
		default:	goto yy51;
		}
yy76:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy77;
		default:	goto yy50;
		}
yy77:
		YYSETCONDITION(yycTYPE_DECL);
#line 77 "qb_parser_re2c.l"
		{ return T_TAG_SHARED; }
#line 469 "qb_parser_re2c.c"
yy78:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy79;
		case 't':	goto yy80;
		default:	goto yy51;
		}
yy79:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy85;
		default:	goto yy51;
		}
yy80:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'u':	goto yy81;
		default:	goto yy51;
		}
yy81:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy82;
		default:	goto yy51;
		}
yy82:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy83;
		default:	goto yy51;
		}
yy83:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy84;
		default:	goto yy50;
		}
yy84:
		YYSETCONDITION(yycTYPE_DECL);
#line 89 "qb_parser_re2c.l"
		{ return T_TAG_RETURN; }
#line 515 "qb_parser_re2c.c"
yy85:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy86;
		default:	goto yy51;
		}
yy86:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy87;
		default:	goto yy51;
		}
yy87:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy88;
		default:	goto yy51;
		}
yy88:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy89;
		default:	goto yy50;
		}
yy89:
		YYSETCONDITION(yycTYPE_DECL);
#line 91 "qb_parser_re2c.l"
		{ return T_TAG_RECEIVE; }
#line 548 "qb_parser_re2c.c"
yy90:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy99;
		default:	goto yy51;
		}
yy91:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy92;
		default:	goto yy51;
		}
yy92:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy93;
		default:	goto yy51;
		}
yy93:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy94;
		default:	goto yy51;
		}
yy94:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy95;
		default:	goto yy51;
		}
yy95:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy96;
		default:	goto yy51;
		}
yy96:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy97;
		default:	goto yy51;
		}
yy97:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy98;
		default:	goto yy50;
		}
yy98:
		YYSETCONDITION(yycTYPE_DECL);
#line 85 "qb_parser_re2c.l"
		{ return T_TAG_PROPERTY; }
#line 605 "qb_parser_re2c.c"
yy99:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy100;
		default:	goto yy51;
		}
yy100:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy101;
		default:	goto yy51;
		}
yy101:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy102;
		default:	goto yy50;
		}
yy102:
		YYSETCONDITION(yycTYPE_DECL);
#line 81 "qb_parser_re2c.l"
		{ return T_TAG_PARAM; }
#line 632 "qb_parser_re2c.c"
yy103:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy111;
		default:	goto yy51;
		}
yy104:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy105;
		default:	goto yy51;
		}
yy105:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy106;
		default:	goto yy51;
		}
yy106:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy107;
		default:	goto yy51;
		}
yy107:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy108;
		default:	goto yy51;
		}
yy108:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy109;
		default:	goto yy51;
		}
yy109:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy110;
		default:	goto yy50;
		}
yy110:
		YYSETCONDITION(yycTYPE_DECL);
#line 79 "qb_parser_re2c.l"
		{ return T_TAG_LEXICAL; }
#line 683 "qb_parser_re2c.c"
yy111:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy112;
		default:	goto yy51;
		}
yy112:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy113;
		default:	goto yy51;
		}
yy113:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy114;
		default:	goto yy50;
		}
yy114:
		YYSETCONDITION(yycTYPE_DECL);
#line 75 "qb_parser_re2c.l"
		{ return T_TAG_LOCAL; }
#line 710 "qb_parser_re2c.c"
yy115:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy122;
		default:	goto yy51;
		}
yy116:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy117;
		default:	goto yy51;
		}
yy117:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy118;
		default:	goto yy51;
		}
yy118:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy119;
		default:	goto yy51;
		}
yy119:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy120;
		default:	goto yy51;
		}
yy120:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy121;
		default:	goto yy50;
		}
yy121:
		YYSETCONDITION(yycPARAM);
#line 53 "qb_parser_re2c.l"
		{ return T_TAG_IMPORT; }
#line 755 "qb_parser_re2c.c"
yy122:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy123;
		default:	goto yy51;
		}
yy123:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy124;
		default:	goto yy51;
		}
yy124:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy125;
		default:	goto yy51;
		}
yy125:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy126;
		default:	goto yy50;
		}
yy126:
		YYSETCONDITION(yycINLINE_PARAM);
#line 47 "qb_parser_re2c.l"
		{ return T_TAG_INLINE; }
#line 788 "qb_parser_re2c.c"
yy127:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy128;
		default:	goto yy51;
		}
yy128:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy129;
		default:	goto yy51;
		}
yy129:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy130;
		default:	goto yy51;
		}
yy130:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy131;
		default:	goto yy51;
		}
yy131:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy132;
		default:	goto yy50;
		}
yy132:
		YYSETCONDITION(yycTYPE_DECL);
#line 73 "qb_parser_re2c.l"
		{ return T_TAG_GLOBAL; }
#line 827 "qb_parser_re2c.c"
yy133:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy134;
		default:	goto yy51;
		}
yy134:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy135;
		default:	goto yy51;
		}
yy135:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy136;
		default:	goto yy51;
		}
yy136:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy137;
		default:	goto yy51;
		}
yy137:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy138;
		default:	goto yy50;
		}
yy138:
		YYSETCONDITION(yycENGINE_PARAM);
#line 39 "qb_parser_re2c.l"
		{ return T_TAG_ENGINE; }
#line 866 "qb_parser_re2c.c"
/* *********************************** */
yyc_INLINE_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy144;
		case '\t':
		case ' ':	goto yy142;
		case 'a':	goto yy146;
		case 'n':	goto yy147;
		default:	goto yy141;
		}
yy141:
yy142:
		++YYCURSOR;
#line 191 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 891 "qb_parser_re2c.c"
yy144:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 896 "qb_parser_re2c.c"
yy146:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy153;
		default:	goto yy141;
		}
yy147:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy148;
		default:	goto yy141;
		}
yy148:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy149;
		default:	goto yy141;
		}
yy149:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy150;
		default:	goto yy141;
		}
yy150:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy151;
		default:	goto yy141;
		}
yy151:
		++YYCURSOR;
#line 51 "qb_parser_re2c.l"
		{ return T_NEVER; }
#line 931 "qb_parser_re2c.c"
yy153:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'w':	goto yy154;
		default:	goto yy141;
		}
yy154:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy155;
		default:	goto yy141;
		}
yy155:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy156;
		default:	goto yy141;
		}
yy156:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 's':	goto yy157;
		default:	goto yy141;
		}
yy157:
		++YYCURSOR;
#line 49 "qb_parser_re2c.l"
		{ return T_ALWAYS; }
#line 960 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy164;
		case '\t':
		case ' ':	goto yy162;
		case '\n':
		case '\r':	goto yy161;
		case '"':	goto yy167;
		case '\'':	goto yy169;
		default:	goto yy166;
		}
yy161:
yy162:
		++YYCURSOR;
#line 191 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 987 "qb_parser_re2c.c"
yy164:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 992 "qb_parser_re2c.c"
yy166:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy161;
		default:	goto yy171;
		}
yy167:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM_DBL_QUOTES);
#line 57 "qb_parser_re2c.l"
		{ goto skip; }
#line 1008 "qb_parser_re2c.c"
yy169:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM_SG_QUOTES);
#line 65 "qb_parser_re2c.l"
		{ goto skip; }
#line 1014 "qb_parser_re2c.c"
yy171:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy173;
		default:	goto yy171;
		}
yy173:
#line 55 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1029 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM_DBL_QUOTES:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy178;
		case '\t':
		case ' ':	goto yy176;
		case '\n':
		case '\r':	goto yy184;
		case '"':	goto yy180;
		default:	goto yy182;
		}
yy176:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy183;
yy177:
#line 61 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1049 "qb_parser_re2c.c"
yy178:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 1054 "qb_parser_re2c.c"
yy180:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM);
#line 59 "qb_parser_re2c.l"
		{ goto skip; }
#line 1060 "qb_parser_re2c.c"
yy182:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy183:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':
		case '"':	goto yy177;
		default:	goto yy182;
		}
yy184:
		++YYCURSOR;
#line 63 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 1076 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM_SG_QUOTES:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy190;
		case '\t':
		case ' ':	goto yy188;
		case '\n':
		case '\r':	goto yy196;
		case '\'':	goto yy192;
		default:	goto yy194;
		}
yy188:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy195;
yy189:
#line 69 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1096 "qb_parser_re2c.c"
yy190:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 1101 "qb_parser_re2c.c"
yy192:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM);
#line 67 "qb_parser_re2c.l"
		{ goto skip; }
#line 1107 "qb_parser_re2c.c"
yy194:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy195:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':
		case '\'':	goto yy189;
		default:	goto yy194;
		}
yy196:
		++YYCURSOR;
#line 71 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 1123 "qb_parser_re2c.c"
/* *********************************** */
yyc_TYPE_DECL:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy203;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '+':
		case '-':
		case '.':
		case '/':
		case ';':
		case '=':
		case '@':
		case '\\':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy200;
		case '\t':
		case ' ':	goto yy201;
		case '$':	goto yy237;
		case '*':	goto yy223;
		case ',':	goto yy229;
		case '0':	goto yy231;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy233;
		case ':':	goto yy227;
		case '<':	goto yy219;
		case '>':	goto yy221;
		case '?':	goto yy225;
		case '[':	goto yy215;
		case ']':	goto yy217;
		case 'b':	goto yy213;
		case 'c':	goto yy212;
		case 'd':	goto yy209;
		case 'f':	goto yy208;
		case 'i':	goto yy205;
		case 'm':	goto yy214;
		case 's':	goto yy211;
		case 'u':	goto yy207;
		case 'v':	goto yy210;
		default:	goto yy235;
		}
yy200:
		YYCURSOR = YYMARKER;
		goto yy232;
yy201:
		++YYCURSOR;
#line 191 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 1228 "qb_parser_re2c.c"
yy203:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 1233 "qb_parser_re2c.c"
yy205:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 'm':	goto yy324;
		case 'n':	goto yy325;
		default:	goto yy236;
		}
yy206:
#line 163 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1244 "qb_parser_re2c.c"
yy207:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy309;
		default:	goto yy236;
		}
yy208:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy298;
		default:	goto yy236;
		}
yy209:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy292;
		default:	goto yy236;
		}
yy210:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy279;
		case 'o':	goto yy280;
		default:	goto yy236;
		}
yy211:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy273;
		default:	goto yy236;
		}
yy212:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'h':	goto yy262;
		case 'o':	goto yy263;
		default:	goto yy236;
		}
yy213:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy255;
		default:	goto yy236;
		}
yy214:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy243;
		default:	goto yy236;
		}
yy215:
		++YYCURSOR;
#line 143 "qb_parser_re2c.l"
		{ return '['; }
#line 1299 "qb_parser_re2c.c"
yy217:
		++YYCURSOR;
#line 145 "qb_parser_re2c.l"
		{ return ']'; }
#line 1304 "qb_parser_re2c.c"
yy219:
		++YYCURSOR;
#line 147 "qb_parser_re2c.l"
		{ return '<'; }
#line 1309 "qb_parser_re2c.c"
yy221:
		++YYCURSOR;
#line 149 "qb_parser_re2c.l"
		{ return '>'; }
#line 1314 "qb_parser_re2c.c"
yy223:
		++YYCURSOR;
#line 151 "qb_parser_re2c.l"
		{ return '*'; }
#line 1319 "qb_parser_re2c.c"
yy225:
		++YYCURSOR;
#line 153 "qb_parser_re2c.l"
		{ return '?'; }
#line 1324 "qb_parser_re2c.c"
yy227:
		++YYCURSOR;
#line 155 "qb_parser_re2c.l"
		{ return ':'; }
#line 1329 "qb_parser_re2c.c"
yy229:
		++YYCURSOR;
#line 157 "qb_parser_re2c.l"
		{ return ','; }
#line 1334 "qb_parser_re2c.c"
yy231:
		yych = (YYCTYPE)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case 'x':	goto yy239;
		default:	goto yy234;
		}
yy232:
#line 159 "qb_parser_re2c.l"
		{ return T_DECIMAL; }
#line 1344 "qb_parser_re2c.c"
yy233:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy234:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy233;
		default:	goto yy232;
		}
yy235:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy236:
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy206;
		default:	goto yy235;
		}
yy237:
		++YYCURSOR;
		YYSETCONDITION(yycVARIABLE_NAME);
#line 165 "qb_parser_re2c.l"
		{ return '$'; }
#line 1438 "qb_parser_re2c.c"
yy239:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy240;
		default:	goto yy200;
		}
yy240:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy240;
		default:	goto yy242;
		}
yy242:
#line 161 "qb_parser_re2c.l"
		{ return T_HEXADECIMAL; }
#line 1497 "qb_parser_re2c.c"
yy243:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy244;
		default:	goto yy236;
		}
yy244:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy245;
		default:	goto yy236;
		}
yy245:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy246;
		default:	goto yy236;
		}
yy246:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy247;
		default:	goto yy236;
		}
yy247:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy248;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy249;
		default:	goto yy235;
		}
yy248:
#line 141 "qb_parser_re2c.l"
		{ return T_TYPE_MATRIX3X3; }
#line 1603 "qb_parser_re2c.c"
yy249:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy206;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy249;
		case 'x':	goto yy251;
		default:	goto yy235;
		}
yy251:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy252;
		default:	goto yy236;
		}
yy252:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy254;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy252;
		default:	goto yy235;
		}
yy254:
#line 139 "qb_parser_re2c.l"
		{ return T_TYPE_MATRIX; }
#line 1782 "qb_parser_re2c.c"
yy255:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy256;
		default:	goto yy236;
		}
yy256:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy257;
		default:	goto yy236;
		}
yy257:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy258;
		case 'e':	goto yy259;
		default:	goto yy235;
		}
yy258:
#line 127 "qb_parser_re2c.l"
		{ return T_TYPE_BOOLEAN; }
#line 1868 "qb_parser_re2c.c"
yy259:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy260;
		default:	goto yy236;
		}
yy260:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy261;
		default:	goto yy236;
		}
yy261:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy258;
		default:	goto yy235;
		}
yy262:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy270;
		default:	goto yy236;
		}
yy263:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy264;
		default:	goto yy236;
		}
yy264:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy265;
		default:	goto yy236;
		}
yy265:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy266;
		default:	goto yy236;
		}
yy266:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy267;
		default:	goto yy236;
		}
yy267:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy268;
		default:	goto yy236;
		}
yy268:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy269;
		default:	goto yy235;
		}
yy269:
#line 133 "qb_parser_re2c.l"
		{ return T_TYPE_COMPLEX; }
#line 2058 "qb_parser_re2c.c"
yy270:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy271;
		default:	goto yy236;
		}
yy271:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy272;
		default:	goto yy235;
		}
yy272:
#line 125 "qb_parser_re2c.l"
		{ return T_TYPE_CHAR; }
#line 2137 "qb_parser_re2c.c"
yy273:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy274;
		default:	goto yy236;
		}
yy274:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy275;
		default:	goto yy236;
		}
yy275:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy276;
		default:	goto yy236;
		}
yy276:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy277;
		default:	goto yy236;
		}
yy277:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy278;
		default:	goto yy235;
		}
yy278:
#line 123 "qb_parser_re2c.l"
		{ return T_TYPE_STRING; }
#line 2234 "qb_parser_re2c.c"
yy279:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy284;
		default:	goto yy236;
		}
yy280:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy281;
		default:	goto yy236;
		}
yy281:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy282;
		default:	goto yy236;
		}
yy282:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy283;
		default:	goto yy235;
		}
yy283:
#line 121 "qb_parser_re2c.l"
		{ return T_TYPE_VOID; }
#line 2325 "qb_parser_re2c.c"
yy284:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy285;
		default:	goto yy236;
		}
yy285:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy286;
		default:	goto yy236;
		}
yy286:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy287;
		default:	goto yy236;
		}
yy287:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy288;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy289;
		default:	goto yy235;
		}
yy288:
#line 137 "qb_parser_re2c.l"
		{ return T_TYPE_VECTOR3; }
#line 2425 "qb_parser_re2c.c"
yy289:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy291;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy289;
		default:	goto yy235;
		}
yy291:
#line 135 "qb_parser_re2c.l"
		{ return T_TYPE_VECTOR; }
#line 2509 "qb_parser_re2c.c"
yy292:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'u':	goto yy293;
		default:	goto yy236;
		}
yy293:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy294;
		default:	goto yy236;
		}
yy294:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy295;
		default:	goto yy236;
		}
yy295:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy296;
		default:	goto yy236;
		}
yy296:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy297;
		default:	goto yy235;
		}
yy297:
#line 115 "qb_parser_re2c.l"
		{ return T_TYPE_DOUBLE; }
#line 2606 "qb_parser_re2c.c"
yy298:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy299;
		default:	goto yy236;
		}
yy299:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy300;
		default:	goto yy236;
		}
yy300:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy301;
		default:	goto yy236;
		}
yy301:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy302;
		case '3':	goto yy303;
		case '6':	goto yy304;
		default:	goto yy235;
		}
yy302:
#line 113 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT; }
#line 2699 "qb_parser_re2c.c"
yy303:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy307;
		default:	goto yy236;
		}
yy304:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy305;
		default:	goto yy236;
		}
yy305:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy306;
		default:	goto yy235;
		}
yy306:
#line 119 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT64; }
#line 2784 "qb_parser_re2c.c"
yy307:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy308;
		default:	goto yy235;
		}
yy308:
#line 117 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT32; }
#line 2857 "qb_parser_re2c.c"
yy309:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy310;
		default:	goto yy236;
		}
yy310:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy311;
		default:	goto yy236;
		}
yy311:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy312;
		case '1':	goto yy315;
		case '3':	goto yy316;
		case '6':	goto yy317;
		case '8':	goto yy313;
		default:	goto yy235;
		}
yy312:
#line 103 "qb_parser_re2c.l"
		{ return T_TYPE_UINT; }
#line 2946 "qb_parser_re2c.c"
yy313:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy314;
		default:	goto yy235;
		}
yy314:
#line 105 "qb_parser_re2c.l"
		{ return T_TYPE_UINT08; }
#line 3019 "qb_parser_re2c.c"
yy315:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '6':	goto yy322;
		default:	goto yy236;
		}
yy316:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy320;
		default:	goto yy236;
		}
yy317:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy318;
		default:	goto yy236;
		}
yy318:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy319;
		default:	goto yy235;
		}
yy319:
#line 111 "qb_parser_re2c.l"
		{ return T_TYPE_UINT64;	}
#line 3110 "qb_parser_re2c.c"
yy320:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy321;
		default:	goto yy235;
		}
yy321:
#line 109 "qb_parser_re2c.l"
		{ return T_TYPE_UINT32; }
#line 3183 "qb_parser_re2c.c"
yy322:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy323;
		default:	goto yy235;
		}
yy323:
#line 107 "qb_parser_re2c.l"
		{ return T_TYPE_UINT16; }
#line 3256 "qb_parser_re2c.c"
yy324:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy343;
		default:	goto yy236;
		}
yy325:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy326;
		default:	goto yy236;
		}
yy326:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy327;
		case '1':	goto yy328;
		case '3':	goto yy329;
		case '6':	goto yy330;
		case '8':	goto yy331;
		case 'e':	goto yy333;
		default:	goto yy235;
		}
yy327:
#line 93 "qb_parser_re2c.l"
		{ return T_TYPE_INT; }
#line 3346 "qb_parser_re2c.c"
yy328:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '6':	goto yy341;
		default:	goto yy236;
		}
yy329:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy339;
		default:	goto yy236;
		}
yy330:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy337;
		default:	goto yy236;
		}
yy331:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy332;
		default:	goto yy235;
		}
yy332:
#line 95 "qb_parser_re2c.l"
		{ return T_TYPE_INT08; }
#line 3437 "qb_parser_re2c.c"
yy333:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy334;
		default:	goto yy236;
		}
yy334:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy335;
		default:	goto yy236;
		}
yy335:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy336;
		default:	goto yy236;
		}
yy336:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy327;
		default:	goto yy235;
		}
yy337:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy338;
		default:	goto yy235;
		}
yy338:
#line 101 "qb_parser_re2c.l"
		{ return T_TYPE_INT64; }
#line 3597 "qb_parser_re2c.c"
yy339:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy340;
		default:	goto yy235;
		}
yy340:
#line 99 "qb_parser_re2c.l"
		{ return T_TYPE_INT32; }
#line 3670 "qb_parser_re2c.c"
yy341:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy342;
		default:	goto yy235;
		}
yy342:
#line 97 "qb_parser_re2c.l"
		{ return T_TYPE_INT16; }
#line 3743 "qb_parser_re2c.c"
yy343:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy344;
		default:	goto yy236;
		}
yy344:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy345;
		default:	goto yy236;
		}
yy345:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy346;
		case '1':
		case '2':
		case '3':
		case '4':	goto yy347;
		default:	goto yy235;
		}
yy346:
#line 131 "qb_parser_re2c.l"
		{ return T_TYPE_IMAGE4; }
#line 3832 "qb_parser_re2c.c"
yy347:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy348;
		default:	goto yy235;
		}
yy348:
#line 129 "qb_parser_re2c.l"
		{ return T_TYPE_IMAGE; }
#line 3905 "qb_parser_re2c.c"
/* *********************************** */
yyc_VARIABLE_NAME:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy354;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy359;
		case '\t':
		case ' ':	goto yy352;
		case '\n':
		case '\r':
		case ';':	goto yy351;
		default:	goto yy356;
		}
yy351:
yy352:
		++YYCURSOR;
#line 174 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 3991 "qb_parser_re2c.c"
yy354:
		++YYCURSOR;
#line 189 "qb_parser_re2c.l"
		{ return 0; }
#line 3996 "qb_parser_re2c.c"
yy356:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':
		case ';':	goto yy358;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy359;
		default:	goto yy356;
		}
yy358:
		YYSETCONDITION(yycTYPE_DECL);
#line 168 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 4071 "qb_parser_re2c.c"
yy359:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':
		case ';':	goto yy361;
		default:	goto yy359;
		}
yy361:
		YYSETCONDITION(yycTYPE_DECL);
#line 171 "qb_parser_re2c.l"
		{ return T_REGEXP; }
#line 4088 "qb_parser_re2c.c"
	}
#line 200 "qb_parser_re2c.l"

}
