/* Generated by re2c 0.13.5 on Wed Apr 02 23:54:00 2014 */
#line 3 "qb_parser_re2c.h"

enum YYCONDTYPE {
	yycINITIAL,
	yycPARAM,
	yycPARAM_DBL_QUOTES,
	yycPARAM_SG_QUOTES,
	yycTYPE_DECL,
	yycVARIABLE_NAME,
	yycCOMMENT,
};
