/* Generated by re2c 0.13.5 */
#line 1 "qb_parser_re2c.l"
/*
  +----------------------------------------------------------------------+
  | PHP Version 5                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997-2012 The PHP Group                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: Chung Leong <cleong@cal.berkeley.edu>                        |
  +----------------------------------------------------------------------+
*/

/* $Id$ */

#include "qb.h"
#include "qb_parser_re2c.h"
#include "qb_parser_bison.h"

#define YYCTYPE				char
#define YYCURSOR 			l->cursor
#define YYMARKER			l->marker
#define YYCONDTYPE			int
#define YYGETCONDITION()	l->condition
#define YYSETCONDITION(c)	l->condition = c

int qb_scan_next_token(qb_lexer_context *l) {

skip:
	l->token = l->cursor; 


#line 41 "qb_parser_re2c.c"
	{
		YYCTYPE yych;
		switch (YYGETCONDITION()) {
		case yycCOMMENT: goto yyc_COMMENT;
		case yycENGINE_PARAM: goto yyc_ENGINE_PARAM;
		case yycINITIAL: goto yyc_INITIAL;
		case yycINLINE_PARAM: goto yyc_INLINE_PARAM;
		case yycPARAM: goto yyc_PARAM;
		case yycPARAM_DBL_QUOTES: goto yyc_PARAM_DBL_QUOTES;
		case yycPARAM_SG_QUOTES: goto yyc_PARAM_SG_QUOTES;
		case yycTYPE_DECL: goto yyc_TYPE_DECL;
		case yycVARIABLE_NAME: goto yyc_VARIABLE_NAME;
		}
/* *********************************** */
yyc_COMMENT:

		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy4;
		case '\t':
		case ' ':	goto yy2;
		case '\n':	goto yy8;
		case '\r':	goto yy10;
		default:	goto yy6;
		}
yy2:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy7;
yy3:
#line 205 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 74 "qb_parser_re2c.c"
yy4:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 79 "qb_parser_re2c.c"
yy6:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy7:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':	goto yy3;
		default:	goto yy6;
		}
yy8:
		++YYCURSOR;
yy9:
		YYSETCONDITION(yycINITIAL);
#line 207 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 96 "qb_parser_re2c.c"
yy10:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case '\n':	goto yy8;
		default:	goto yy9;
		}
/* *********************************** */
yyc_ENGINE_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy16;
		case '\t':
		case ' ':	goto yy14;
		case 'q':	goto yy18;
		default:	goto yy13;
		}
yy13:
		YYCURSOR = YYMARKER;
		goto yy20;
yy14:
		++YYCURSOR;
#line 211 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 128 "qb_parser_re2c.c"
yy16:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 133 "qb_parser_re2c.c"
yy18:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy19;
		default:	goto yy13;
		}
yy19:
		yych = (YYCTYPE)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case '-':	goto yy21;
		default:	goto yy20;
		}
yy20:
#line 61 "qb_parser_re2c.l"
		{ return T_ENGINE_QB; }
#line 149 "qb_parser_re2c.c"
yy21:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy22;
		case 'n':	goto yy23;
		default:	goto yy13;
		}
yy22:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy30;
		default:	goto yy13;
		}
yy23:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy24;
		default:	goto yy13;
		}
yy24:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy25;
		default:	goto yy13;
		}
yy25:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy26;
		default:	goto yy13;
		}
yy26:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy27;
		default:	goto yy13;
		}
yy27:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy28;
		default:	goto yy13;
		}
yy28:
		++YYCURSOR;
#line 63 "qb_parser_re2c.l"
		{ return T_ENGINE_QB_NATIVE; }
#line 197 "qb_parser_re2c.c"
yy30:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy31;
		default:	goto yy13;
		}
yy31:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy32;
		default:	goto yy13;
		}
yy32:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy33;
		default:	goto yy13;
		}
yy33:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy34;
		default:	goto yy13;
		}
yy34:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy35;
		default:	goto yy13;
		}
yy35:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy36;
		default:	goto yy13;
		}
yy36:
		++YYCURSOR;
#line 65 "qb_parser_re2c.l"
		{ return T_ENGINE_QB_BYTECODE; }
#line 238 "qb_parser_re2c.c"
/* *********************************** */
yyc_INITIAL:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy42;
		case '\t':
		case ' ':	goto yy40;
		case '\n':	goto yy49;
		case '\r':	goto yy51;
		case '*':	goto yy46;
		case '/':	goto yy48;
		case '@':	goto yy44;
		default:	goto yy52;
		}
yy40:
		++YYCURSOR;
#line 211 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 265 "qb_parser_re2c.c"
yy42:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 270 "qb_parser_re2c.c"
yy44:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 'e':	goto yy57;
		case 'g':	goto yy58;
		case 'i':	goto yy59;
		case 'l':	goto yy60;
		case 'p':	goto yy61;
		case 'r':	goto yy62;
		case 's':	goto yy63;
		case 'v':	goto yy64;
		default:	goto yy53;
		}
yy45:
		YYSETCONDITION(yycCOMMENT);
#line 203 "qb_parser_re2c.l"
		goto yyc_COMMENT;
#line 288 "qb_parser_re2c.c"
yy46:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy47;
		default:	goto yy52;
		}
yy47:
#line 196 "qb_parser_re2c.l"
		{ goto skip; }
#line 302 "qb_parser_re2c.c"
yy48:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '*':	goto yy54;
		default:	goto yy53;
		}
yy49:
		++YYCURSOR;
yy50:
#line 200 "qb_parser_re2c.l"
		{ return T_COMMENT; }
#line 314 "qb_parser_re2c.c"
yy51:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '\n':	goto yy49;
		default:	goto yy50;
		}
yy52:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy53:
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy45;
		default:	goto yy52;
		}
yy54:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '*':	goto yy55;
		default:	goto yy53;
		}
yy55:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy56;
		default:	goto yy52;
		}
yy56:
#line 198 "qb_parser_re2c.l"
		{ goto skip; }
#line 352 "qb_parser_re2c.c"
yy57:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy135;
		default:	goto yy53;
		}
yy58:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy129;
		default:	goto yy53;
		}
yy59:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy118;
		case 'n':	goto yy117;
		default:	goto yy53;
		}
yy60:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy106;
		case 'o':	goto yy105;
		default:	goto yy53;
		}
yy61:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy92;
		case 'r':	goto yy93;
		default:	goto yy53;
		}
yy62:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy80;
		default:	goto yy53;
		}
yy63:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'h':	goto yy68;
		case 't':	goto yy69;
		default:	goto yy53;
		}
yy64:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy65;
		default:	goto yy53;
		}
yy65:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy66;
		default:	goto yy53;
		}
yy66:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy67;
		default:	goto yy52;
		}
yy67:
		YYSETCONDITION(yycTYPE_DECL);
#line 107 "qb_parser_re2c.l"
		{ return T_TAG_VAR; }
#line 425 "qb_parser_re2c.c"
yy68:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy75;
		default:	goto yy53;
		}
yy69:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy70;
		default:	goto yy53;
		}
yy70:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy71;
		default:	goto yy53;
		}
yy71:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy72;
		default:	goto yy53;
		}
yy72:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy73;
		default:	goto yy53;
		}
yy73:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy74;
		default:	goto yy52;
		}
yy74:
		YYSETCONDITION(yycTYPE_DECL);
#line 103 "qb_parser_re2c.l"
		{ return T_TAG_STATIC; }
#line 470 "qb_parser_re2c.c"
yy75:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy76;
		default:	goto yy53;
		}
yy76:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy77;
		default:	goto yy53;
		}
yy77:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy78;
		default:	goto yy53;
		}
yy78:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy79;
		default:	goto yy52;
		}
yy79:
		YYSETCONDITION(yycTYPE_DECL);
#line 97 "qb_parser_re2c.l"
		{ return T_TAG_SHARED; }
#line 503 "qb_parser_re2c.c"
yy80:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy81;
		case 't':	goto yy82;
		default:	goto yy53;
		}
yy81:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy87;
		default:	goto yy53;
		}
yy82:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'u':	goto yy83;
		default:	goto yy53;
		}
yy83:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy84;
		default:	goto yy53;
		}
yy84:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy85;
		default:	goto yy53;
		}
yy85:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy86;
		default:	goto yy52;
		}
yy86:
		YYSETCONDITION(yycTYPE_DECL);
#line 109 "qb_parser_re2c.l"
		{ return T_TAG_RETURN; }
#line 549 "qb_parser_re2c.c"
yy87:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy88;
		default:	goto yy53;
		}
yy88:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy89;
		default:	goto yy53;
		}
yy89:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy90;
		default:	goto yy53;
		}
yy90:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy91;
		default:	goto yy52;
		}
yy91:
		YYSETCONDITION(yycTYPE_DECL);
#line 111 "qb_parser_re2c.l"
		{ return T_TAG_RECEIVE; }
#line 582 "qb_parser_re2c.c"
yy92:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy101;
		default:	goto yy53;
		}
yy93:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy94;
		default:	goto yy53;
		}
yy94:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy95;
		default:	goto yy53;
		}
yy95:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy96;
		default:	goto yy53;
		}
yy96:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy97;
		default:	goto yy53;
		}
yy97:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy98;
		default:	goto yy53;
		}
yy98:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy99;
		default:	goto yy53;
		}
yy99:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy100;
		default:	goto yy52;
		}
yy100:
		YYSETCONDITION(yycTYPE_DECL);
#line 105 "qb_parser_re2c.l"
		{ return T_TAG_PROPERTY; }
#line 639 "qb_parser_re2c.c"
yy101:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy102;
		default:	goto yy53;
		}
yy102:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy103;
		default:	goto yy53;
		}
yy103:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy104;
		default:	goto yy52;
		}
yy104:
		YYSETCONDITION(yycTYPE_DECL);
#line 101 "qb_parser_re2c.l"
		{ return T_TAG_PARAM; }
#line 666 "qb_parser_re2c.c"
yy105:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy113;
		default:	goto yy53;
		}
yy106:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy107;
		default:	goto yy53;
		}
yy107:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy108;
		default:	goto yy53;
		}
yy108:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy109;
		default:	goto yy53;
		}
yy109:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy110;
		default:	goto yy53;
		}
yy110:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy111;
		default:	goto yy53;
		}
yy111:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy112;
		default:	goto yy52;
		}
yy112:
		YYSETCONDITION(yycTYPE_DECL);
#line 99 "qb_parser_re2c.l"
		{ return T_TAG_LEXICAL; }
#line 717 "qb_parser_re2c.c"
yy113:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy114;
		default:	goto yy53;
		}
yy114:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy115;
		default:	goto yy53;
		}
yy115:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy116;
		default:	goto yy52;
		}
yy116:
		YYSETCONDITION(yycTYPE_DECL);
#line 95 "qb_parser_re2c.l"
		{ return T_TAG_LOCAL; }
#line 744 "qb_parser_re2c.c"
yy117:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy124;
		default:	goto yy53;
		}
yy118:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy119;
		default:	goto yy53;
		}
yy119:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy120;
		default:	goto yy53;
		}
yy120:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy121;
		default:	goto yy53;
		}
yy121:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy122;
		default:	goto yy53;
		}
yy122:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy123;
		default:	goto yy52;
		}
yy123:
		YYSETCONDITION(yycPARAM);
#line 73 "qb_parser_re2c.l"
		{ return T_TAG_IMPORT; }
#line 789 "qb_parser_re2c.c"
yy124:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy125;
		default:	goto yy53;
		}
yy125:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy126;
		default:	goto yy53;
		}
yy126:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy127;
		default:	goto yy53;
		}
yy127:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy128;
		default:	goto yy52;
		}
yy128:
		YYSETCONDITION(yycINLINE_PARAM);
#line 67 "qb_parser_re2c.l"
		{ return T_TAG_INLINE; }
#line 822 "qb_parser_re2c.c"
yy129:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy130;
		default:	goto yy53;
		}
yy130:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy131;
		default:	goto yy53;
		}
yy131:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy132;
		default:	goto yy53;
		}
yy132:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy133;
		default:	goto yy53;
		}
yy133:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy134;
		default:	goto yy52;
		}
yy134:
		YYSETCONDITION(yycTYPE_DECL);
#line 93 "qb_parser_re2c.l"
		{ return T_TAG_GLOBAL; }
#line 861 "qb_parser_re2c.c"
yy135:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy136;
		default:	goto yy53;
		}
yy136:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy137;
		default:	goto yy53;
		}
yy137:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy138;
		default:	goto yy53;
		}
yy138:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy139;
		default:	goto yy53;
		}
yy139:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy140;
		default:	goto yy52;
		}
yy140:
		YYSETCONDITION(yycENGINE_PARAM);
#line 59 "qb_parser_re2c.l"
		{ return T_TAG_ENGINE; }
#line 900 "qb_parser_re2c.c"
/* *********************************** */
yyc_INLINE_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy146;
		case '\t':
		case ' ':	goto yy144;
		case 'a':	goto yy148;
		case 'n':	goto yy149;
		default:	goto yy143;
		}
yy143:
yy144:
		++YYCURSOR;
#line 211 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 925 "qb_parser_re2c.c"
yy146:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 930 "qb_parser_re2c.c"
yy148:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy155;
		default:	goto yy143;
		}
yy149:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy150;
		default:	goto yy143;
		}
yy150:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'v':	goto yy151;
		default:	goto yy143;
		}
yy151:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy152;
		default:	goto yy143;
		}
yy152:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy153;
		default:	goto yy143;
		}
yy153:
		++YYCURSOR;
#line 71 "qb_parser_re2c.l"
		{ return T_NEVER; }
#line 965 "qb_parser_re2c.c"
yy155:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'w':	goto yy156;
		default:	goto yy143;
		}
yy156:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy157;
		default:	goto yy143;
		}
yy157:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'y':	goto yy158;
		default:	goto yy143;
		}
yy158:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 's':	goto yy159;
		default:	goto yy143;
		}
yy159:
		++YYCURSOR;
#line 69 "qb_parser_re2c.l"
		{ return T_ALWAYS; }
#line 994 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy166;
		case '\t':
		case ' ':	goto yy164;
		case '\n':
		case '\r':	goto yy163;
		case '"':	goto yy169;
		case '\'':	goto yy171;
		default:	goto yy168;
		}
yy163:
yy164:
		++YYCURSOR;
#line 211 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 1021 "qb_parser_re2c.c"
yy166:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 1026 "qb_parser_re2c.c"
yy168:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy163;
		default:	goto yy173;
		}
yy169:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM_DBL_QUOTES);
#line 77 "qb_parser_re2c.l"
		{ goto skip; }
#line 1042 "qb_parser_re2c.c"
yy171:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM_SG_QUOTES);
#line 85 "qb_parser_re2c.l"
		{ goto skip; }
#line 1048 "qb_parser_re2c.c"
yy173:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':	goto yy175;
		default:	goto yy173;
		}
yy175:
#line 75 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1063 "qb_parser_re2c.c"
/* *********************************** */
yyc_PARAM_DBL_QUOTES:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy180;
		case '\t':
		case ' ':	goto yy178;
		case '\n':	goto yy186;
		case '\r':	goto yy188;
		case '"':	goto yy182;
		default:	goto yy184;
		}
yy178:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy185;
yy179:
#line 81 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1083 "qb_parser_re2c.c"
yy180:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 1088 "qb_parser_re2c.c"
yy182:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM);
#line 79 "qb_parser_re2c.l"
		{ goto skip; }
#line 1094 "qb_parser_re2c.c"
yy184:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy185:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':
		case '"':	goto yy179;
		default:	goto yy184;
		}
yy186:
		++YYCURSOR;
yy187:
#line 83 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 1111 "qb_parser_re2c.c"
yy188:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case '\n':	goto yy186;
		default:	goto yy187;
		}
/* *********************************** */
yyc_PARAM_SG_QUOTES:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy193;
		case '\t':
		case ' ':	goto yy191;
		case '\n':	goto yy199;
		case '\r':	goto yy201;
		case '\'':	goto yy195;
		default:	goto yy197;
		}
yy191:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		goto yy198;
yy192:
#line 89 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1137 "qb_parser_re2c.c"
yy193:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 1142 "qb_parser_re2c.c"
yy195:
		++YYCURSOR;
		YYSETCONDITION(yycPARAM);
#line 87 "qb_parser_re2c.l"
		{ goto skip; }
#line 1148 "qb_parser_re2c.c"
yy197:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy198:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':
		case '\'':	goto yy192;
		default:	goto yy197;
		}
yy199:
		++YYCURSOR;
yy200:
#line 91 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 1165 "qb_parser_re2c.c"
yy201:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case '\n':	goto yy199;
		default:	goto yy200;
		}
/* *********************************** */
yyc_TYPE_DECL:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy207;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '+':
		case '-':
		case '.':
		case '/':
		case ';':
		case '=':
		case '@':
		case '\\':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy204;
		case '\t':
		case ' ':	goto yy205;
		case '$':	goto yy241;
		case '*':	goto yy227;
		case ',':	goto yy233;
		case '0':	goto yy235;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy237;
		case ':':	goto yy231;
		case '<':	goto yy223;
		case '>':	goto yy225;
		case '?':	goto yy229;
		case '[':	goto yy219;
		case ']':	goto yy221;
		case 'b':	goto yy217;
		case 'c':	goto yy216;
		case 'd':	goto yy213;
		case 'f':	goto yy212;
		case 'i':	goto yy209;
		case 'm':	goto yy218;
		case 's':	goto yy215;
		case 'u':	goto yy211;
		case 'v':	goto yy214;
		default:	goto yy239;
		}
yy204:
		YYCURSOR = YYMARKER;
		goto yy236;
yy205:
		++YYCURSOR;
#line 211 "qb_parser_re2c.l"
		{
		if(l->token + 1 == l->cursor) {
			// just white space--jump over it
			goto skip;
		} else {
			// there was something there that didn't match anything
			return T_UNEXPECTED;
		}
	}
#line 1276 "qb_parser_re2c.c"
yy207:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 1281 "qb_parser_re2c.c"
yy209:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 'm':	goto yy328;
		case 'n':	goto yy329;
		default:	goto yy240;
		}
yy210:
#line 183 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 1292 "qb_parser_re2c.c"
yy211:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy313;
		default:	goto yy240;
		}
yy212:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy302;
		default:	goto yy240;
		}
yy213:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy296;
		default:	goto yy240;
		}
yy214:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy283;
		case 'o':	goto yy284;
		default:	goto yy240;
		}
yy215:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy277;
		default:	goto yy240;
		}
yy216:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'h':	goto yy266;
		case 'o':	goto yy267;
		default:	goto yy240;
		}
yy217:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy259;
		default:	goto yy240;
		}
yy218:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy247;
		default:	goto yy240;
		}
yy219:
		++YYCURSOR;
#line 163 "qb_parser_re2c.l"
		{ return '['; }
#line 1347 "qb_parser_re2c.c"
yy221:
		++YYCURSOR;
#line 165 "qb_parser_re2c.l"
		{ return ']'; }
#line 1352 "qb_parser_re2c.c"
yy223:
		++YYCURSOR;
#line 167 "qb_parser_re2c.l"
		{ return '<'; }
#line 1357 "qb_parser_re2c.c"
yy225:
		++YYCURSOR;
#line 169 "qb_parser_re2c.l"
		{ return '>'; }
#line 1362 "qb_parser_re2c.c"
yy227:
		++YYCURSOR;
#line 171 "qb_parser_re2c.l"
		{ return '*'; }
#line 1367 "qb_parser_re2c.c"
yy229:
		++YYCURSOR;
#line 173 "qb_parser_re2c.l"
		{ return '?'; }
#line 1372 "qb_parser_re2c.c"
yy231:
		++YYCURSOR;
#line 175 "qb_parser_re2c.l"
		{ return ':'; }
#line 1377 "qb_parser_re2c.c"
yy233:
		++YYCURSOR;
#line 177 "qb_parser_re2c.l"
		{ return ','; }
#line 1382 "qb_parser_re2c.c"
yy235:
		yych = (YYCTYPE)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case 'x':	goto yy243;
		default:	goto yy238;
		}
yy236:
#line 179 "qb_parser_re2c.l"
		{ return T_DECIMAL; }
#line 1392 "qb_parser_re2c.c"
yy237:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy238:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy237;
		default:	goto yy236;
		}
yy239:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
yy240:
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy210;
		default:	goto yy239;
		}
yy241:
		++YYCURSOR;
		YYSETCONDITION(yycVARIABLE_NAME);
#line 185 "qb_parser_re2c.l"
		{ return '$'; }
#line 1486 "qb_parser_re2c.c"
yy243:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy244;
		default:	goto yy204;
		}
yy244:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy244;
		default:	goto yy246;
		}
yy246:
#line 181 "qb_parser_re2c.l"
		{ return T_HEXADECIMAL; }
#line 1545 "qb_parser_re2c.c"
yy247:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy248;
		default:	goto yy240;
		}
yy248:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy249;
		default:	goto yy240;
		}
yy249:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy250;
		default:	goto yy240;
		}
yy250:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy251;
		default:	goto yy240;
		}
yy251:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy252;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy253;
		default:	goto yy239;
		}
yy252:
#line 161 "qb_parser_re2c.l"
		{ return T_TYPE_MATRIX3X3; }
#line 1651 "qb_parser_re2c.c"
yy253:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy210;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy253;
		case 'x':	goto yy255;
		default:	goto yy239;
		}
yy255:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy256;
		default:	goto yy240;
		}
yy256:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy258;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy256;
		default:	goto yy239;
		}
yy258:
#line 159 "qb_parser_re2c.l"
		{ return T_TYPE_MATRIX; }
#line 1830 "qb_parser_re2c.c"
yy259:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy260;
		default:	goto yy240;
		}
yy260:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy261;
		default:	goto yy240;
		}
yy261:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy262;
		case 'e':	goto yy263;
		default:	goto yy239;
		}
yy262:
#line 147 "qb_parser_re2c.l"
		{ return T_TYPE_BOOLEAN; }
#line 1916 "qb_parser_re2c.c"
yy263:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy264;
		default:	goto yy240;
		}
yy264:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy265;
		default:	goto yy240;
		}
yy265:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy262;
		default:	goto yy239;
		}
yy266:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy274;
		default:	goto yy240;
		}
yy267:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'm':	goto yy268;
		default:	goto yy240;
		}
yy268:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'p':	goto yy269;
		default:	goto yy240;
		}
yy269:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy270;
		default:	goto yy240;
		}
yy270:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy271;
		default:	goto yy240;
		}
yy271:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'x':	goto yy272;
		default:	goto yy240;
		}
yy272:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy273;
		default:	goto yy239;
		}
yy273:
#line 153 "qb_parser_re2c.l"
		{ return T_TYPE_COMPLEX; }
#line 2106 "qb_parser_re2c.c"
yy274:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy275;
		default:	goto yy240;
		}
yy275:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy276;
		default:	goto yy239;
		}
yy276:
#line 145 "qb_parser_re2c.l"
		{ return T_TYPE_CHAR; }
#line 2185 "qb_parser_re2c.c"
yy277:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy278;
		default:	goto yy240;
		}
yy278:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy279;
		default:	goto yy240;
		}
yy279:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy280;
		default:	goto yy240;
		}
yy280:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy281;
		default:	goto yy240;
		}
yy281:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy282;
		default:	goto yy239;
		}
yy282:
#line 143 "qb_parser_re2c.l"
		{ return T_TYPE_STRING; }
#line 2282 "qb_parser_re2c.c"
yy283:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'c':	goto yy288;
		default:	goto yy240;
		}
yy284:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'i':	goto yy285;
		default:	goto yy240;
		}
yy285:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'd':	goto yy286;
		default:	goto yy240;
		}
yy286:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy287;
		default:	goto yy239;
		}
yy287:
#line 141 "qb_parser_re2c.l"
		{ return T_TYPE_VOID; }
#line 2373 "qb_parser_re2c.c"
yy288:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy289;
		default:	goto yy240;
		}
yy289:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy290;
		default:	goto yy240;
		}
yy290:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy291;
		default:	goto yy240;
		}
yy291:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy292;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy293;
		default:	goto yy239;
		}
yy292:
#line 157 "qb_parser_re2c.l"
		{ return T_TYPE_VECTOR3; }
#line 2473 "qb_parser_re2c.c"
yy293:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy295;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy293;
		default:	goto yy239;
		}
yy295:
#line 155 "qb_parser_re2c.l"
		{ return T_TYPE_VECTOR; }
#line 2557 "qb_parser_re2c.c"
yy296:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'u':	goto yy297;
		default:	goto yy240;
		}
yy297:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'b':	goto yy298;
		default:	goto yy240;
		}
yy298:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'l':	goto yy299;
		default:	goto yy240;
		}
yy299:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy300;
		default:	goto yy240;
		}
yy300:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy301;
		default:	goto yy239;
		}
yy301:
#line 135 "qb_parser_re2c.l"
		{ return T_TYPE_DOUBLE; }
#line 2654 "qb_parser_re2c.c"
yy302:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'o':	goto yy303;
		default:	goto yy240;
		}
yy303:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy304;
		default:	goto yy240;
		}
yy304:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy305;
		default:	goto yy240;
		}
yy305:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy306;
		case '3':	goto yy307;
		case '6':	goto yy308;
		default:	goto yy239;
		}
yy306:
#line 133 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT; }
#line 2747 "qb_parser_re2c.c"
yy307:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy311;
		default:	goto yy240;
		}
yy308:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy309;
		default:	goto yy240;
		}
yy309:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy310;
		default:	goto yy239;
		}
yy310:
#line 139 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT64; }
#line 2832 "qb_parser_re2c.c"
yy311:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy312;
		default:	goto yy239;
		}
yy312:
#line 137 "qb_parser_re2c.l"
		{ return T_TYPE_FLOAT32; }
#line 2905 "qb_parser_re2c.c"
yy313:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'n':	goto yy314;
		default:	goto yy240;
		}
yy314:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy315;
		default:	goto yy240;
		}
yy315:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy316;
		case '1':	goto yy319;
		case '3':	goto yy320;
		case '6':	goto yy321;
		case '8':	goto yy317;
		default:	goto yy239;
		}
yy316:
#line 123 "qb_parser_re2c.l"
		{ return T_TYPE_UINT; }
#line 2994 "qb_parser_re2c.c"
yy317:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy318;
		default:	goto yy239;
		}
yy318:
#line 125 "qb_parser_re2c.l"
		{ return T_TYPE_UINT08; }
#line 3067 "qb_parser_re2c.c"
yy319:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '6':	goto yy326;
		default:	goto yy240;
		}
yy320:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy324;
		default:	goto yy240;
		}
yy321:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy322;
		default:	goto yy240;
		}
yy322:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy323;
		default:	goto yy239;
		}
yy323:
#line 131 "qb_parser_re2c.l"
		{ return T_TYPE_UINT64;	}
#line 3158 "qb_parser_re2c.c"
yy324:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy325;
		default:	goto yy239;
		}
yy325:
#line 129 "qb_parser_re2c.l"
		{ return T_TYPE_UINT32; }
#line 3231 "qb_parser_re2c.c"
yy326:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy327;
		default:	goto yy239;
		}
yy327:
#line 127 "qb_parser_re2c.l"
		{ return T_TYPE_UINT16; }
#line 3304 "qb_parser_re2c.c"
yy328:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy347;
		default:	goto yy240;
		}
yy329:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 't':	goto yy330;
		default:	goto yy240;
		}
yy330:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy331;
		case '1':	goto yy332;
		case '3':	goto yy333;
		case '6':	goto yy334;
		case '8':	goto yy335;
		case 'e':	goto yy337;
		default:	goto yy239;
		}
yy331:
#line 113 "qb_parser_re2c.l"
		{ return T_TYPE_INT; }
#line 3394 "qb_parser_re2c.c"
yy332:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '6':	goto yy345;
		default:	goto yy240;
		}
yy333:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '2':	goto yy343;
		default:	goto yy240;
		}
yy334:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case '4':	goto yy341;
		default:	goto yy240;
		}
yy335:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy336;
		default:	goto yy239;
		}
yy336:
#line 115 "qb_parser_re2c.l"
		{ return T_TYPE_INT08; }
#line 3485 "qb_parser_re2c.c"
yy337:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy338;
		default:	goto yy240;
		}
yy338:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy339;
		default:	goto yy240;
		}
yy339:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'r':	goto yy340;
		default:	goto yy240;
		}
yy340:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy331;
		default:	goto yy239;
		}
yy341:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy342;
		default:	goto yy239;
		}
yy342:
#line 121 "qb_parser_re2c.l"
		{ return T_TYPE_INT64; }
#line 3645 "qb_parser_re2c.c"
yy343:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy344;
		default:	goto yy239;
		}
yy344:
#line 119 "qb_parser_re2c.l"
		{ return T_TYPE_INT32; }
#line 3718 "qb_parser_re2c.c"
yy345:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy346;
		default:	goto yy239;
		}
yy346:
#line 117 "qb_parser_re2c.l"
		{ return T_TYPE_INT16; }
#line 3791 "qb_parser_re2c.c"
yy347:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'g':	goto yy348;
		default:	goto yy240;
		}
yy348:
		yych = (YYCTYPE)*++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy349;
		default:	goto yy240;
		}
yy349:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy350;
		case '1':
		case '2':
		case '3':
		case '4':	goto yy351;
		default:	goto yy239;
		}
yy350:
#line 151 "qb_parser_re2c.l"
		{ return T_TYPE_IMAGE4; }
#line 3880 "qb_parser_re2c.c"
yy351:
		++YYCURSOR;
		switch ((yych = (YYCTYPE)*YYCURSOR)) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy352;
		default:	goto yy239;
		}
yy352:
#line 149 "qb_parser_re2c.l"
		{ return T_TYPE_IMAGE; }
#line 3953 "qb_parser_re2c.c"
/* *********************************** */
yyc_VARIABLE_NAME:
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy358;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy363;
		case '\t':
		case ' ':	goto yy356;
		case '\n':
		case '\r':
		case ';':	goto yy355;
		default:	goto yy360;
		}
yy355:
yy356:
		++YYCURSOR;
#line 194 "qb_parser_re2c.l"
		{ return T_UNEXPECTED; }
#line 4039 "qb_parser_re2c.c"
yy358:
		++YYCURSOR;
#line 209 "qb_parser_re2c.l"
		{ return 0; }
#line 4044 "qb_parser_re2c.c"
yy360:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':
		case ';':	goto yy362;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto yy363;
		default:	goto yy360;
		}
yy362:
		YYSETCONDITION(yycTYPE_DECL);
#line 188 "qb_parser_re2c.l"
		{ return T_LABEL; }
#line 4119 "qb_parser_re2c.c"
yy363:
		++YYCURSOR;
		yych = (YYCTYPE)*YYCURSOR;
		switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\r':
		case ' ':
		case ';':	goto yy365;
		default:	goto yy363;
		}
yy365:
		YYSETCONDITION(yycTYPE_DECL);
#line 191 "qb_parser_re2c.l"
		{ return T_REGEXP; }
#line 4136 "qb_parser_re2c.c"
	}
#line 220 "qb_parser_re2c.l"

}
